#Common
COMPRESS="n"
FOR_EXYNOS="y"
EROFS="y"

#Exnos
EXYNOS_TARGET="p3s"
EXYNOS_MODELS=("c1s" c2s c1slte c2slte)

#Snapdragon
SNAPDRAGON_TARGET="something"
SNAPDRAGON_MODELS=(c2s)

#Vendor
CREATE_VENDOR="y"
COMMON_VENDOR="y"
PATCH_VENDOR="y"

VENDOR_DELETE="C2xDelete"
VENDOR_COPY="C2xCopy"
VENDOR_MISC="C2xMisc"


#Project Structure
ROOT_DIR=$(dirname "$(readlink -f "$0")")
WORKING_DIR=$ROOT_DIR/Working
EXTERNAL_DIR=$ROOT_DIR/External
STOCK_DIR=$ROOT_DIR/Stock
ASSETS_DIR=$ROOT_DIR/Assets
RESOURCES_DIR=$ASSETS_DIR/Resources
SCRIPT_DIR=$ASSETS_DIR/Scripts
HELPER_DIR=$SCRIPT_DIR/Helper
MODIFICATION_DIR=$SCRIPT_DIR/Modifications

#Formating
RESET="\033[0m"
SUCCESS_FG="\033[32m"
TITLE_BG="\033[104m"
TITLE_FG="\033[30m"
PROCESS_FG="\033[95m"
ERROR_FG="\033[31m"
WARNING_FG="\033[33m"

OVERWRITE="\r\033[K"

TITLEWIDTH=45



